### ISSUE TITLE
删除时焦点错误

### ISSUE THREAD

**Issue by Qibest** [disburden/vercoder_inputer#2]
比如验证码一共6位，输入123456 。按一下删除键，再输入 7,期望结果是 123457 。
而现在却是 12347 还有一位未输入。

**Comment by disburden** [comment]
嗯,是有这个问题,我找个时间看看别人是怎么弄的,等有空了就改

**Comment by disburden** [comment]
@Qibest
我已经修正了这个问题,你可以升级到0.7.0试看看
另外我在样式中增加了获取焦点的文本框下划线的颜色,这样可以很清楚的知道当前删除和输入的是哪个位置.

我先关闭这个问题,有问题欢迎随时提出!
