### ISSUE TITLE
删除的时候每个字符都要删除两次？

### ISSUE THREAD

**Issue by fengqiangboy** [disburden/vercoder_inputer#3]
删除的时候每个字符都要删除两次？

**Comment by wukuy** [comment]
一样的情况

**Comment by disburden** [comment]
好吧,我看了其他人的做法,好像都只删一次,找个时间我也改成直接删

**Comment by wukuy** [comment]
> 解决了，更新到0.8就行了，另外还参考了美团网，增加了复位（）方法，如果验证码错误的话可以直接重置



> 好吧，我看了其他人的做法，好像都只删一次，找个时间我也改成直接删

3Q
