### ISSUE TITLE
Unable to reopen the keyboard once it was closed

### ISSUE THREAD

**Issue by exilonX** [disburden/vercoder_inputer#5]
If you try to close the keyboard you are unable to reopen it if you click on the inputs or in any other way. 
Expected behavior - the keyboard should reopen if you click on any of the input fields.

**Comment by disburden** [comment]
Is it on android?

**Comment by exilonX** [comment]
I tested on android and iphone and if I close the keyboard I cannot open it again. F
My flutter version is: 

Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git                                                Framework • revision 5391447fae (3 months ago) • 2018-11-29 19:41:26 -0800                                             Engine • revision 7375a0f414                                                                                           Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
--

**Comment by disburden** [comment]
I restored the ability to tap the inputer to show the keyboard.
You can upgrade to 0.8.1 and give it a try.
Contact me if you have any questions.
